
package com.coder.dream.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IsmpEngine", targetNamespace = "http://ws.dream.coder.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IsmpEngine {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.coder.dream.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyServiceConsume", targetNamespace = "http://ws.dream.coder.com/", className = "com.coder.dream.ws.NotifyServiceConsume")
    @ResponseWrapper(localName = "notifyServiceConsumeResponse", targetNamespace = "http://ws.dream.coder.com/", className = "com.coder.dream.ws.NotifyServiceConsumeResponse")
    public Response notifyServiceConsume(
        @WebParam(name = "arg0", targetNamespace = "")
        ServiceConsumeNotifyReq arg0);

}
