
package com.coder.dream.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IsmpEngineService", targetNamespace = "http://ws.dream.coder.com/", wsdlLocation = "http://localhost:8080/cxf/services/IsmpEngineService?wsdl")
public class IsmpEngineService
    extends Service
{

    private final static URL ISMPENGINESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISMPENGINESERVICE_EXCEPTION;
    private final static QName ISMPENGINESERVICE_QNAME = new QName("http://ws.dream.coder.com/", "IsmpEngineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/cxf/services/IsmpEngineService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISMPENGINESERVICE_WSDL_LOCATION = url;
        ISMPENGINESERVICE_EXCEPTION = e;
    }

    public IsmpEngineService() {
        super(__getWsdlLocation(), ISMPENGINESERVICE_QNAME);
    }

    public IsmpEngineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISMPENGINESERVICE_QNAME, features);
    }

    public IsmpEngineService(URL wsdlLocation) {
        super(wsdlLocation, ISMPENGINESERVICE_QNAME);
    }

    public IsmpEngineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISMPENGINESERVICE_QNAME, features);
    }

    public IsmpEngineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsmpEngineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IsmpEngine
     */
    @WebEndpoint(name = "IsmpEnginePort")
    public IsmpEngine getIsmpEnginePort() {
        return super.getPort(new QName("http://ws.dream.coder.com/", "IsmpEnginePort"), IsmpEngine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsmpEngine
     */
    @WebEndpoint(name = "IsmpEnginePort")
    public IsmpEngine getIsmpEnginePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dream.coder.com/", "IsmpEnginePort"), IsmpEngine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISMPENGINESERVICE_EXCEPTION!= null) {
            throw ISMPENGINESERVICE_EXCEPTION;
        }
        return ISMPENGINESERVICE_WSDL_LOCATION;
    }

}
